name: Test & Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scroll_builder
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Prepare pub credentials
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > "$PUB_CACHE/credentials.json"

      - name: Copy README into package directory
        run: cp ../README.md ./README.md

      - name: Copy LICENSE into package directory
        run: cp ../LICENSE ./LICENSE

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish Package
        run: flutter pub publish -f