name: scroll_builder
description: A widget that makes it easier to implement effects on scrollable widgets such as scale or fade.
version: 0.0.1
homepage: https://github.com/xiprox/scroll_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
